### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by yamadahideto** [yamadahideto/EnigmaCraft#30]
issueを作成しました。
ご確認のほどよろしくお願いします！

### 概要
自作の謎を投稿したり、AIを使用して謎を生成したり自由に謎の投稿・閲覧・解答するためのサービスです。 謎の正解数に応じてポイントが付与され、ポイント数によってバッチの取得・ランキング表示などを予定しており 回答者としても出題者としても楽しめるサービスです。

*** 

### 実装予定の機能

- [ ] sorceryでのユーザー登録機能
- [ ] ログイン機能
- [ ] 問題の新規登録機能
- [ ] プロフィール編集 (ニックネーム・メールアドレス変更)
- [ ] ジャンル機能
- [ ] 検索機能
- [ ] 正解時ポイント処理
- [ ] ユーザーランキング表示
- [ ] OpenAI APIでの画像生成機能
- [ ] X (Twitter)シェア機能
- [ ] 一度正解した問題は回答できないようにする

*** 

### 必要なページ
- [ ] 新規登録ページ
- [ ] ログインページ
- [ ] トップページ
- [ ] 通常の画像謎の投稿画面
- [ ] 画像生成での投稿画面
- [ ] 謎の編集画面
- [ ] 詳細・回答ページ
- [ ] 正解・不正解時のモーダル表示
- [ ] プロフィール画面
- [ ] プロフィール編集画面
- [ ] ログイン前とログイン後の一覧表示
- [ ] ユーザーランキング画面
- [ ] パスワード再設定画面

**Comment by ghost** [comment]
概ねOKです！
LGTMです！

**Comment by yamadahideto** [comment]
ありがとうございます！！
