### ISSUE TITLE
卒業制作　レビュー依頼

### ISSUE THREAD

**Issue by yamadahideto** [yamadahideto/EnigmaCraft#68]
お忙しいところ恐れ入りますが、ご確認のほどよろしくお願いいたします！
https://github.com/yamadahideto/EnigmaCraft

## 各種情報
**サービス名**
Enigmaportals

**サービスURL**
https://enigmaportals.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
READMEレビュー時に実装予定だった機能が実装できているかがわかるように記載してください
- [x] ユーザー登録機能
- [x] ログイン機能
- [x] ニックネーム・アバター変更機能
- [x] 謎投稿機能（画像投稿含む）
- [x] 謎閲覧機能（未ログインでも閲覧可能）
- [x] 謎への回答機能（未ログインでも回答可能）
- [x] AI 謎画像生成機能
- [x] AI 謎生成機能
- [x] 謎編集機能
- [x] 謎削除機能
- [x] 正解時にポイント付与
- [x] タイトル・カテゴリ 検索機能
- [x] ユーザーランキング

## READMEレビュー時から変更した機能
開発途中でMVPリリース時点で作らなくなった機能や追加した機能があれば記載してください
- [ ] パスワード変更機能 
後々、Google認証のみでのログインを考えています。

## サービスイメージがわかるようなスクリーンショット等
特に管理画面など通常ユーザーが触れない機能があったら共有をお願いします

###  謎一覧画面
[![Image from Gyazo](https://i.gyazo.com/8f63779a6eeec26c7000d9ecbfa3c6aa.png)](https://gyazo.com/8f63779a6eeec26c7000d9ecbfa3c6aa)

### 謎作成(AI画像生成)
[![Image from Gyazo](https://i.gyazo.com/cab333fdc06e9550cbef384f0dc9099f.png)](https://gyazo.com/cab333fdc06e9550cbef384f0dc9099f)

### 謎作成 (画像投稿)
[![Image from Gyazo](https://i.gyazo.com/cc529a6fcbff6ecffb66a3bd50622197.png)](https://gyazo.com/cc529a6fcbff6ecffb66a3bd50622197)

### ユーザーマイページ 
[![Image from Gyazo](https://i.gyazo.com/959ee5221a03fe4c8cccf043041107cc.png)](https://gyazo.com/959ee5221a03fe4c8cccf043041107cc)

### マイページ編集
[![Image from Gyazo](https://i.gyazo.com/375ae3ed338fb660f649581c1a9d5985.png)](https://gyazo.com/375ae3ed338fb660f649581c1a9d5985)

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。

**Comment by yamadahideto** [comment]
土屋さんありがとうございます！！！
